# Generated by Django 5.0.3 on 2024-04-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category_alter_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cook_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prep_time',
        ),
    ]
