# Generated by Django 5.0.3 on 2024-04-19 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_cook_time_recipe_time_remove_recipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
