# Generated by Django 5.0.3 on 2024-04-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_servings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategory',
            name='description',
        ),
    ]
