# Generated by Django 5.0.3 on 2024-04-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipeingredient_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
    ]
