# Generated by Django 5.0.3 on 2024-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_ingredient_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQam3maltN38Ks8qVSfYHsrzSaNOtjIFnX09mub8GeAmg&s', max_length=500),
        ),
    ]
