# Generated by Django 5.0.3 on 2024-04-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_instruction_remove_recipe_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='name',
            new_name='instruction',
        ),
    ]
