# Generated by Django 5.0.3 on 2024-04-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.CharField(default='https://t4.ftcdn.net/jpg/02/15/28/55/360_F_215285525_fqG9SPnXZfOrwFxHzqI6d1hHPVmdSUSx.jpg', max_length=500),
        ),
    ]
