# Generated by Django 5.0.4 on 2024-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
